-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:66aba577c23f07e8c4baa77bbe831329$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "bar.png",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 40 },
				textureRect = { x = 2, y = 568, width = 320, height = 40 },
				spriteSourceSize = { width = 320, height = 40 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bar2.png",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 82 },
				textureRect = { x = 2, y = 484, width = 320, height = 82 },
				spriteSourceSize = { width = 320, height = 82 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bkg_cor.png",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 480 },
				textureRect = { x = 2, y = 2, width = 320, height = 480 },
				spriteSourceSize = { width = 320, height = 480 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "drink.png",
				spriteColorRect = { x = 7, y = 4, width = 71, height = 168 },
				textureRect = { x = 422, y = 167, width = 71, height = 168 },
				spriteSourceSize = { width = 79, height = 188 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hamburger.png",
				spriteColorRect = { x = 4, y = 4, width = 96, height = 67 },
				textureRect = { x = 324, y = 149, width = 96, height = 67 },
				spriteSourceSize = { width = 102, height = 73 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hotdog.png",
				spriteColorRect = { x = 5, y = 0, width = 118, height = 63 },
				textureRect = { x = 324, y = 84, width = 118, height = 63 },
				spriteSourceSize = { width = 126, height = 67 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icecream.png",
				spriteColorRect = { x = 4, y = 4, width = 120, height = 80 },
				textureRect = { x = 324, y = 2, width = 120, height = 80 },
				spriteSourceSize = { width = 126, height = 88 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icecream2.png",
				spriteColorRect = { x = 1, y = 5, width = 43, height = 93 },
				textureRect = { x = 324, y = 218, width = 43, height = 93 },
				spriteSourceSize = { width = 47, height = 101 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icecream3.png",
				spriteColorRect = { x = 2, y = 9, width = 46, height = 106 },
				textureRect = { x = 446, y = 59, width = 46, height = 106 },
				spriteSourceSize = { width = 50, height = 118 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "orange.png",
				spriteColorRect = { x = 1, y = 2, width = 56, height = 55 },
				textureRect = { x = 446, y = 2, width = 56, height = 55 },
				spriteSourceSize = { width = 58, height = 59 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

